
/* eslint-disable @typescript-eslint/ban-ts-comment */
//@ts-nocheck
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unused-vars */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openDatabase(path: string) : Promise<null> {
    return await TAURI_INVOKE("open_database", { path });
},
async closeDatabase() : Promise<null> {
    return await TAURI_INVOKE("close_database");
},
async getDatabase() : Promise<string> {
    return await TAURI_INVOKE("get_database");
},
async getPrefs() : Promise<Prefs> {
    return await TAURI_INVOKE("get_prefs");
},
async setPrefs(prefs: Prefs) : Promise<null> {
    return await TAURI_INVOKE("set_prefs", { prefs });
},
async resolvePath(path: string) : Promise<string> {
    return await TAURI_INVOKE("resolve_path", { path });
},
async addSticker(assets: AssetEnum[], name: string | null, description: string | null, collectionId: string, tags: string[], deleteOriginal: boolean) : Promise<null> {
    return await TAURI_INVOKE("add_sticker", { assets, name, description, collectionId, tags, deleteOriginal });
},
async searchCollections(name: string) : Promise<Collection[]> {
    return await TAURI_INVOKE("search_collections", { name });
},
async getCollections(order: GetCollectionsOrder, limit: number, cursor: string | null) : Promise<Collection[]> {
    return await TAURI_INVOKE("get_collections", { order, limit, cursor });
},
async addCollection(collection: InsertCollectionQuery) : Promise<string> {
    return await TAURI_INVOKE("add_collection", { collection });
},
async getAppPrefs() : Promise<AppPrefs> {
    return await TAURI_INVOKE("get_app_prefs");
},
async setAppPrefs(appPrefs: AppPrefs) : Promise<null> {
    return await TAURI_INVOKE("set_app_prefs", { appPrefs });
},
async whoami() : Promise<string> {
    return await TAURI_INVOKE("whoami");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppPrefs = { database_history: string[] }
export type Asset = ({ type: "text" } & AssetText) | ({ type: "image" } & AssetImage) | ({ type: "video" } & AssetVideo)
export type AssetEnum = { type: "text"; c: string } | { type: "image"; c: string } | { type: "video"; c: string }
export type AssetImage = { id: string; image: string; create_at: string; sha256: string | null }
export type AssetText = { id: string; text: string; create_at: string; sha256: string | null }
export type AssetVideo = { id: string; video: string; create_at: string; sha256: string | null }
export type Collection = { id: string; name: string; description: string | null; author: string | null; create_at: string; modified_at: string; tags: string[]; preview: Asset | null }
export type GetCollectionsOrder = "ASC" | "DESC"
export type InsertCollectionQuery = { name: string; description: string | null; author: string | null }
export type Prefs = { copy_assets_on_add?: boolean; delete_assets_on_add?: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
