/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '/dash': RouteRecordInfo<'/dash', '/dash', Record<never, never>, Record<never, never>>,
    '/dash/(dash)': RouteRecordInfo<'/dash/(dash)', '/dash', Record<never, never>, Record<never, never>>,
    '/dash/add': RouteRecordInfo<'/dash/add', '/dash/add', Record<never, never>, Record<never, never>>,
    '/dash/collections': RouteRecordInfo<'/dash/collections', '/dash/collections', Record<never, never>, Record<never, never>>,
    '/dash/fav': RouteRecordInfo<'/dash/fav', '/dash/fav', Record<never, never>, Record<never, never>>,
    '/dash/pref': RouteRecordInfo<'/dash/pref', '/dash/pref', Record<never, never>, Record<never, never>>,
    '/dash/search/[search]': RouteRecordInfo<'/dash/search/[search]', '/dash/search/:search', { search: ParamValue<true> }, { search: ParamValue<false> }>,
    '/dash/trash': RouteRecordInfo<'/dash/trash', '/dash/trash', Record<never, never>, Record<never, never>>,
  }
}
